language: objective-c
osx_image: xcode7.2

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - WORKSPACE_IOS="iOS/RxCache.xcworkspace"
    - WORKSPACE_OSX="OSX/RxCache.xcworkspace"
    - IOS_FRAMEWORK_SCHEME="iOS"
    - OSX_FRAMEWORK_SCHEME="OSX"
    - IOS_SDK=iphonesimulator9.2
    - OSX_SDK=macosx10.11

  matrix:
    - DESTINATION="OS=9.2,name=iPhone 6"      SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
    - DESTINATION="arch=x86_64"               SCHEME="$OSX_FRAMEWORK_SCHEME"     SDK="$OSX_SDK"     RUN_TESTS="YES"

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script: 
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests iOS workspace if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE_IOS" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE_IOS" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Build Framework in Debug and Run Tests OSX workspace if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE_OSX" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE_OSX" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

notifications:
  email: false